language: node_js
node_js: node
services: mongodb
env:
  matrix:
    secure: Qvz86n0nUYck9+BjQVkA3OCIf5NMkdgg/ByAxlN97D9eVQaGIdC/GJed79uGkeM9TjJn8I/icLM6vUprPzJ3VodrBPkJ+h8XA1kS8VO3jH1ax+SMRahXYRjxAQz73o7hXv1je1aD1uCg7Iw4s8YUWD4HBGbXt+uKhmLOsMpVkxenca/EjufI05vSlIjZpuNjcODE64TlBABp2aIsuxbWVZIQA9QYhAEGHyQHU9Lt49fWyyE0D4Yc0rBM/B3lsbi4HYNBcNf3kUl08Vjf30uFaegc1IFDrjVuYcRm6ajEYNcZt/97CQdewiWm8M86WHUtuOzbcn3I3/k2z614R506Sotfqmk9VcJdgzHT/r//d3bkfTMrGtKvohp+IP/BPLFjxdPhFDIXTJp0aUyWUBq7PsTEJTaZjigka4YhVlyKQDde0j4FRbSFOvOfo8UpUP6maFx6FACNMAvyB4L/yI9dhymn0xIAL3he7Dph0QDWACVAMwbyHxe+VvE0MkEs00ZYH9WIZGi4qVa3IIYSFBNLKBi9BV5R4WNIwGCEcak4pSeLrIYn/Db/jdmrtJnCHH4WxFPfDuwNs0cluyWICyY4LzAzZOjiT5xMp8bsVctDsCqhsC6wSxhDcML/LMuo9+eu/N2qpA3sRvrTMG7aI7SI/mjFakwkE/ls7lsNFtmvPJ0=
